###########################################################################
#
#   cpu.mak
#
#   Rules for building CPU cores
#
#   Copyright Nicola Salmoria and the MAME Team.
#   Visit http://mamedev.org for licensing and usage restrictions.
#
###########################################################################


CPUSRC = .
CPUOBJ = .




#-------------------------------------------------
# Motorola 6809
#-------------------------------------------------

OBJDIRS += .
CPUOBJS += m6809.o
DASMOBJS += 6809dasm.o


m6809.o:	m6809.c \
							m6809.h \
							6809ops.c \
							6809tbl.c



